import { describe, expect, it } from 'vitest';
import { extractLayers, indexGcodeLayers, previewSourceFor } from './layer-filter';
import { planPreview } from './budget';

const enc = new TextEncoder();
const dec = new TextDecoder();

function layer(n: number): string {
  const z = (n + 1) * 0.2;
  return `;LAYER_CHANGE\n;Z:${z.toFixed(1)}\n;HEIGHT:0.2\nG1 Z${z.toFixed(1)}\nG1 X${n} Y${n} E.5\n`;
}
function sample(layers: number, config = true): string {
  return '; HEADER_BLOCK_START\n; generated by OrcaSlicer 2.4.2\n; HEADER_BLOCK_END\n\n; EXECUTABLE_BLOCK_START\nG90 ; abs\nM83\nG28\nG1 Y140 E10\n'
    + Array.from({ length: layers }, (_, n) => layer(n)).join('')
    + 'M104 S0\n; EXECUTABLE_BLOCK_END\n\n' + (config ? '; CONFIG_BLOCK_START\n; brim_width = 5\n; CONFIG_BLOCK_END\n' : '');
}

describe('indexGcodeLayers', () => {
  it('finds layer starts, Z heights and the end of the executable block', () => {
    const bytes = enc.encode(sample(4));
    const index = indexGcodeLayers(bytes);
    expect(index.layerCount).toBe(4);
    expect(index.layerZ).toEqual([0.2, 0.4, 0.6, 0.8]);
    expect(dec.decode(bytes.subarray(index.layerStarts[0]!, index.layerStarts[0]! + 14))).toBe(';LAYER_CHANGE\n');
    expect(dec.decode(bytes.subarray(index.bodyEnd, index.bodyEnd + 24))).toBe('; EXECUTABLE_BLOCK_END\n\n');
  });

  it('handles CRLF, indented markers, and text without layer markers', () => {
    expect(indexGcodeLayers(enc.encode(sample(3).replaceAll('\n', '\r\n'))).layerCount).toBe(3);
    expect(indexGcodeLayers(enc.encode('G28\nG1 X1 E1\n')).layerCount).toBe(0);
    expect(indexGcodeLayers(new Uint8Array()).layerCount).toBe(0);
    expect(indexGcodeLayers(enc.encode('G1 X1 ;LAYER_CHANGE inline\n')).layerCount).toBe(0);
  });

  it('leaves Z undefined when the marker has no Z line', () => {
    expect(indexGcodeLayers(enc.encode(';LAYER_CHANGE\nG1 X1\n')).layerZ).toEqual([undefined]);
  });
});

describe('extractLayers', () => {
  it('keeps the start section for windows that include layer 0', () => {
    const bytes = enc.encode(sample(6));
    const out = dec.decode(extractLayers(bytes, indexGcodeLayers(bytes), 0, 1));
    expect(out).toContain('; HEADER_BLOCK_START');
    expect(out).toContain('G1 Y140 E10');
    expect(out.match(/;LAYER_CHANGE/g)).toHaveLength(2);
  });

  it('keeps only modal commands (not the prime line) when the window skips layer 0, and drops the config block', () => {
    const bytes = enc.encode(sample(6));
    const out = dec.decode(extractLayers(bytes, indexGcodeLayers(bytes), 2, 3));
    expect(out.startsWith('G90\nM83\n;LAYER_CHANGE')).toBe(true);
    expect(out).not.toContain('G1 Y140 E10');
    expect(out).not.toContain('G28');
    expect(out).toContain('G1 X2 Y2 E.5');
    expect(out).toContain('G1 X3 Y3 E.5');
    for (const dropped of ['X0 Y0', 'X1 Y1', 'X4 Y4', 'X5 Y5', 'brim_width']) expect(out).not.toContain(dropped);
    expect(out.match(/;LAYER_CHANGE/g)).toHaveLength(2);
    expect(out).toContain('; EXECUTABLE_BLOCK_END');
  });

  it('clamps the range, returns the whole layered body for the full range, and never mutates the input', () => {
    const bytes = enc.encode(sample(3));
    const copy = bytes.slice();
    const index = indexGcodeLayers(bytes);
    expect(dec.decode(extractLayers(bytes, index, -5, 99)).match(/;LAYER_CHANGE/g)).toHaveLength(3);
    expect(dec.decode(extractLayers(bytes, index, 2, 1)).match(/;LAYER_CHANGE/g)).toBeNull();
    expect(bytes).toEqual(copy);
  });

  it('returns a byte-identical copy when no layer markers exist', () => {
    const bytes = enc.encode('G28\nG1 X1 E1\n');
    const out = extractLayers(bytes, indexGcodeLayers(bytes), 0, 3);
    expect(out).toEqual(bytes);
    expect(out).not.toBe(bytes);
  });

  it('last layer stops before the end-of-program config block', () => {
    const bytes = enc.encode(sample(2));
    const out = dec.decode(extractLayers(bytes, indexGcodeLayers(bytes), 1, 1));
    expect(out.trimEnd().endsWith('; EXECUTABLE_BLOCK_END')).toBe(true);
  });
});

describe('previewSourceFor', () => {
  const layers = 400;
  const bytes = enc.encode(sample(layers));
  const index = indexGcodeLayers(bytes);
  const plan = (gcodeBytes: number, tier: 'standard' | 'full', currentLayer: number, minimumStage?: 'window') =>
    planPreview({ gcodeBytes, tier, totalLayers: layers, currentLayer, minimumStage });

  it('all-visible sends the full text with a 0..current range', () => {
    const p = plan(bytes.byteLength, 'full', 9);
    expect(p.stage).toBe('all-visible');
    const src = previewSourceFor(bytes, index, p, 9)!;
    expect(src.bytes.byteLength).toBe(bytes.byteLength);
    expect(src.layerRange).toEqual([0, 9]);
  });

  it('window sends fewer bytes than the full text and draws every filtered layer', () => {
    const p = plan(bytes.byteLength, 'full', 200, 'window');
    expect(p.stage).toBe('window');
    const src = previewSourceFor(bytes, index, p, 200)!;
    expect(src.bytes.byteLength).toBeLessThan(bytes.byteLength / 10);
    expect(src.layerRange).toBeNull();
    expect(dec.decode(src.bytes).match(/;LAYER_CHANGE/g)).toHaveLength(3); // 198..200
  });

  it('decimated falls back to a single-layer window, smaller than the window rung', () => {
    const huge = plan(60_000_000, 'standard', 200);
    const src = previewSourceFor(bytes, index, { ...huge, stage: 'decimated' }, 200)!;
    expect(dec.decode(src.bytes).match(/;LAYER_CHANGE/g)).toHaveLength(1);
    expect(src.layerRange).toBeNull();
  });

  it('does not clip text without layer markers', () => {
    const plain = enc.encode('G28\nG1 X1 E1\n');
    const p = planPreview({ gcodeBytes: plain.byteLength, tier: 'full', totalLayers: 1, currentLayer: 0 });
    expect(previewSourceFor(plain, indexGcodeLayers(plain), p, 0)!.layerRange).toBeNull();
  });

  it('unavailable produces no source', () => {
    expect(previewSourceFor(bytes, index, plan(1e12, 'standard', 1), 1)).toBeNull();
  });
});
